server:
  port: 8088
spring:
  application:
    name: nacosmcpboot
  config:
    import:
      - nacos:springaidemoconfig?group=DEFAULT_GROUP  # 注意后缀名
#  作为配置中心和注册中心使用
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
  ai:
    # spring ai 配置
    mcp:
      # 作为mcp服务端的配置
      server:
        name: nacosmcpserver   # MCP服务名称
        version: 1.0.0            # 服务版本
        type: SYNC                # 调用类型：SYNC（同步）或ASYNC（异步）

    alibaba:
      # mcp服务端注册到nacos上
      mcp:
        nacos:
          server-addr: localhost:8848          # 替换为你的 Nacos 地址
          namespace: public    # Nacos 命名空间 ID（默认为public）
          username: nacos           # 开源控制台用户名
          password: nacos          # 开源控制台密码
          registry:
            enabled: true   # 是否开启服务注册
labs:
  siliconflow:
    api-key: sk-nelxcpuwepgvvxbwbyvbbmfyeairkamgannlpwsxftuufyvh #修改为你的key
    baseUrl: https://api.siliconflow.cn/
    completionsPath: /v1/chat/completions
    embeddingsPath: /v1/embeddings
  ark:
    api-key: d0de3cf9-1c42-4af9-b8ab-8c96b5d9e860 #修改为你的key
    baseUrl: https://ark.cn-beijing.volces.com/api/
    completionsPath: /v3/chat/completions
    embeddingsPath: /v3/embeddings
logging:
  level:
    root: info
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: info  #你可以改为debug
