services:

  backend:
    container_name: spring-ai-alibaba-playground
    image: spring-ai-alibaba-playground:57180df
    environment:
      - AI_DASHSCOPE_API_KEY=${AI_DASHSCOPE_API_KEY}
      - WEB_SEARCH_API_KEY=${WEB_SEARCH_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - spring-ai-alibaba

  frontend:
    container_name: spring-ai-alibaba-playground-frontend
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "3000:80"
    networks:
      - spring-ai-alibaba

networks:
  spring-ai-alibaba:
    driver: bridge
